# Generated by Django 2.2.3 on 2019-07-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190712_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='patronymic',
            field=models.CharField(default='', max_length=255, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='', max_length=255, verbose_name='Номер телефона'),
        ),
    ]
