# Generated by Django 2.2.3 on 2019-07-09 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('slug', models.CharField(default='', max_length=255)),
                ('params', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('available', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Category')),
            ],
        ),
    ]
