# Generated by Django 2.2.3 on 2019-07-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
