# Generated by Django 2.2.3 on 2019-07-09 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commerce', '0004_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('item_total_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_total_price', models.DecimalField(decimal_places=2, max_digits=40)),
                ('cart_total_amount', models.PositiveIntegerField(default=0)),
                ('items', models.ManyToManyField(blank=True, to='commerce.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
