# Generated by Django 2.2.3 on 2019-07-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='to_carousel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30),
        ),
    ]
