# Generated by Django 2.2.3 on 2019-07-10 06:51

import commerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_auto_20190709_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='', upload_to=commerce.models.image_folder),
        ),
    ]
