# Generated by Django 2.2.3 on 2019-07-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20190710_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total_price',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item_total_price',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(default='', max_length=30),
        ),
    ]
