# Generated by Django 2.2.3 on 2019-07-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_auto_20190710_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_total_price',
            field=models.DecimalField(decimal_places=2, max_digits=40),
        ),
    ]
