# Generated by Django 2.2.3 on 2019-07-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart_items',
            new_name='cart',
        ),
    ]
