# Generated by Django 2.2.3 on 2019-07-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0021_auto_20190714_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('Самовывоз', 'Самовывоз'), ('Доставка', 'Доставка')], default=('Самовывоз', 'Самовывоз'), max_length=50, verbose_name='Способ доставки*'),
        ),
    ]
